services:
  client:
    build: ./client
    image: ajaymare/vortex-client:latest
    container_name: vortex-client
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SERVER_HOST=${SERVER_HOST:-10.0.0.100}
    restart: unless-stopped
